### ISSUE TITLE
Vyber platformy na vyvoj

### ISSUE THREAD

**Issue by stingel** [TIS2017/DiscGolf#3]

**Comment by stingel** [comment]
[ ] - Testovanie **Beautiful Soup** v prostredi Visual Studio Code

**Comment by stingel** [comment]
# **Python HTML parser**
- **Kniznica**: BeautifulSoup (https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- **Praca**: BS4 ma vybornu dokumentaciu, parsovanie je pomerne jednoduche
- **IDE**: Visual Studio Code 
- **OS**: macOS Sierra
- **Instalacia**: vsetky balicky som instaloval cez terminal, konkretne cez prikaz PIP, niektore balicky mali problem s pristupovymi pravami ale za par minut googlenia sa dal vzdy najst jednoduchy fix.
- **Ukazka**:
<img width="385" alt="screen shot 2017-10-08 at 11 49 47" src="https://user-images.githubusercontent.com/7633817/31315985-19bf7160-ac24-11e7-8e38-34e9183de014.png">

# **Python DB Connector**
- **Kniznica**: Psycopg2 (http://initd.org/psycopg/docs/)
- **Praca**: Znovu pormerne jednoducha
- **IDE**: Visual Studio Code 
- **Instalacia**: "pip install psycopg2"
- **Ukazka**:
<img width="675" alt="screen shot 2017-10-08 at 11 51 40" src="https://user-images.githubusercontent.com/7633817/31316016-c4a96dd8-ac24-11e7-87ac-eb1a255bb7f8.png">

# **Python Web Builder**
- **Framework**: Django (https://docs.djangoproject.com/en/1.11/)
- **Praca**: S djangom som pracoval prvy raz, jednoduchy turorial, za par minut sa to da cele rozbehat
- **IDE/nastroje**: Visual Studio Code, terminal
- **Instalacia**: "pip install Django"
- **Ukazka**:
<img width="272" alt="screen shot 2017-10-08 at 12 36 28" src="https://user-images.githubusercontent.com/7633817/31316048-79e70f5c-ac25-11e7-917e-796562fe67cb.png">

**Comment by ondrejicka4** [comment]
# Web scraping & parsing

- Jazyk: Python 3.5 + BeautifulSoup 4 Library
- Parser: lxml
- IDE: PyCharm/Python IDLE 
- Inštalácia: ako sa preukázalo, bs4 bolo potrebné nainštalovať cez pip3
Dôvod pre bs4: spokojnosť používateľov, praktická knižnica, pomerne pochopiteľný tutorial

# Database

- Databáza: PostgreSQL
- DB Adapter: psycopg2 (Python)

**Comment by stingel** [comment]
Zhodli sme sa na tom, ze sa bude vyvijat v jazyku Python, na parsovanie webu sa pouzije BS4, ako databazovy system sa pozuije PostreSQL a ako webovy framework sa pouzije Flask.
