### ISSUE TITLE
je tu málo issues

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2017/DiscGolf#5]
to sa okrem katalógu požiadaviek na ničom nerobí?

vždy platí, že nie je možné robiť na projekte nič bez toho, aby na to nebol vytvorený issue! a komunikácia o tom, čo sa robí prebieha tu. napravte to a potom tento issue zatvorte, ďakujem.

**Comment by stingel** [comment]
Zdravim, manazment prace riesime cez Trello nakolko je to daleko jednoduchsie a prehladnejsie. Chcem sa teda spytat a ci staci vzdy hodit screenshot alebo tu musi byt vsetko explicitne riesene tu? @pavelpetrovic

**Comment by pavelpetrovic** [comment]
dakujem, pridajte sem, prosim, samostatny issue, ze manazment prace sa robi cez trello a pridajte nejake pristupove udaje, aby som sa tam vedel dostat. okrem toho, pre mna to nie je ani jednoduchsie ani prehladnejsie kvoli kazdemu projektu sa logovat kade-tade.

**Comment by stingel** [comment]
@pavelpetrovic pristupove udaje som Vam hodil do mailu.
